package de.kaniba.navigator;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FrameDesign extends HorizontalLayout {
	protected CssLayout menuContainer;
	protected HorizontalLayout menuTitle;
	protected Image logo;
	protected Button menuToggle;
	protected VerticalLayout content;
	protected CssLayout menuPart;

	public FrameDesign() {
		Design.read(this);
	}
}
