package de.kaniba.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class RegisterDesign extends Panel {
	protected TextField nameField;
	protected TextField firstNameField;
	protected TextField emailField;
	protected PasswordField passwordField;
	protected PasswordField repeatPasswordField;
	protected DateField birthdateField;
	protected TextField cityField;
	protected TextField streetField;
	protected TextField numberField;
	protected TextField zipField;
	protected Button submitButton;

	public RegisterDesign() {
		Design.read(this);
	}
}
