package com.example.designertest;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.declarative.Design;
import org.vaadin.teemu.ratingstars.RatingStars;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BarView extends GridLayout {
	protected GridLayout leftGrid;
	protected Image barImage;
	protected Label barNameLabel;
	protected Panel infoPanel;
	protected GridLayout messageAreaGrid;
	protected Panel messagePanel;
	protected Button sendMessageButton;
	protected GridLayout ratingLayout;
	protected RatingStars starTotal;
	protected RatingStars starAtmosphere;
	protected RatingStars starMusic;
	protected RatingStars starPrice;
	protected RatingStars starPeople;
	protected Button rateButton;

	public BarView() {
		Design.read(this);
	}
}
