package com.example.designertest;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Register extends FormLayout {
	protected TextField lastNameField;
	protected TextField firstNameField;
	protected TextField emailField;
	protected PasswordField passwordField;
	protected PasswordField passwordRepeatField;
	protected PopupDateField birthdayField;
	protected TextField cityField;
	protected TextField zipCodeField;
	protected TextField streetField;
	protected TextField numberFIeld;
	protected Button registerButton;

	public Register() {
		Design.read(this);
	}
}
